# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pagseguro', 'PagSeguro'), ('paypal', 'Paypal'), ('deposit', 'Depósito')], max_length=20, verbose_name='Opção de pagamento'),
        ),
    ]
