# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20160921_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_option',
            field=models.CharField(choices=[('pagseguro', 'PagSeguro'), ('paypal', 'Paypal'), ('deposit', 'Depósito')], default='deposito', max_length=20, verbose_name='Opção de pagamento'),
        ),
    ]
